SpriteLink/NIPAP

- nipap-www/nipapwww/public/app.js
- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/services.js
- nipap-www/nipapwww/public/templates/prefix_form.html
- nipap-www/nipapwww/templates/base.html
Re-implementation of functionality missed when rebuilding web UI with
AngularJS. The node field on the add/edit prefix-page should be enabled
when adding a prefix with max prefix length (/32 for IPv4 and /128 for
IPv6), no matter what prefix type has been selected.
I chose to place the code in a service which is injected into the prefix
add and prefix edit controllers.
Fixes #675
> www-ui: Enable node-field for max prefix length

- pynipap/pynipap.py
If status hasn't been set we should default to whatever the backend
thinks ('assigned') but as pynipap used its default value of None, the
backend would try to honour that.
This changes that so we only send the status value to the backend if its
not None.
Fixes #668.
> Fix pynipap status value

- nipap-www/nipapwww/public/directives.js
Removed a race condition which caused the VRF field on the add prefix
page to be reset when the VRF was set on page load (when adding a prefix
from another prefix or from a pool).
Fixes #673
> www-ui: Make sure VRF field stays populated

- nipap/nipap/backend.py
Trying to assign addresses from an empty pool would give a weird error
message ("VRF must be the same as the pools implied VRF"). Since we run
find_free_prefix after we look if the requested VRF is equal to the
pools implied VRF I have introduced a check earlier on in the code to
make sure the implied VRF is set (which means there are prefixes in the
pool). The result is an error message that is much more relatable.
Fixes #685
> backend: fix error message for empty pool

- nipap-cli/nipap_cli/nipap_cli.py
- tests/nipaptest.py
The 'nipap vrf list ...' command constructed it's own query dict instead
of relying on the smart_search_vrf method of the backend which is weird
and inconsistent as both prefix and pool listing uses the respective
smart_search functions.
> cli: use smart search for VRF listing

- nipap-cli/nipap_cli/nipap_cli.py
We perform a query to retrieve the affected prefixes if we are
performing a recursive query but it wouldn't get called in time under
certain scenarios. By moving the query a tad earlier in the code we make
sure that we always have the result we need.
Fixes #670.
> cli: fix traceback on recursive remove

- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/services.js
- nipap-www/nipapwww/public/templates/prefix_add.html
- nipap-www/nipapwww/public/templates/prefix_form.html
Fix of the incomplete fix for #675, which did not handle prefixes being
allocated from pools or other prefixes, only manual additions.
Fixes #686
> www: Fix node input for other allocation methods

- nipap-www/nipapwww/public/templates/prefix_form.html
The input field has to be filled in when we are manually adding a new
prefix. Since it shouldn't be entered at all for from-pool or
from-prefix operations we use a conditional ng-required statement that
checks that the allocation method is 'manual'.
Fixes #482.
> www: require prefix field on manual assignment

- nipap-cli/nipap_cli/nipap_cli.py
To calculate correct statistics there needs to be at least one member
prefix and the default prefix length need to be set for the address
family in question. When this is not the case, the CLI would throw a
traceback but by adding some checks (similar to the ones in the web UI)
we avoid division by None and instead display a message stating that
statistics aren't available and why.
I've added another issue (#693) to track the issue that the backend
calculates statistics differently for prefixes and addresses.
Fixes #672.
> cli: fix viewing of pool statistics

- nipap/nipap/authlib.py
- nipap/nipap/backend.py
- nipap/nipap/nipapconfig.py
- nipap/xmlbench.py
- pynipap/pynipap.py
- tests/nipaptest.py
- tests/upgrade-before.py
It's generally a bad idea since they are only instantiated once (at declaration time).
An example:
```python
>>> def tst(arg=[]):
...     arg.append(len(arg))
...     print arg
...
>>> tst()
[0]
>>> tst()
[0, 1]
>>> tst()
[0, 1, 2]
```
> Don't use mutable default arguments

- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
The current LDAP Auth does not work with AD, and having the current one doing both I think would have been a bit messy, so created a new one for AD.
You use your samAccountName as username, it does UPN style LDAP bind with username@domain, where domain is from the config file.
It checks for group memberships, you have to be member of either the rogroup or rwgroup to be authenticated. If you are a member of both groups you will get rw access.
Fixes #607
> Add Active Directory LDAP Auth support

- nipap/nipap/authlib.py
This moves the import of the ldap module from the start of nipapd to
when it is actually needed. If LDAP isn't configured as backend
authentication then it will never be used.
If LDAP authentication is enabled but the ldap module is not available,
we will log an error message when someone tries to authenticate. It is
NOT logged on startup of nipapd which might not be completely obvious.
We would need to rework larger parts of the code to achieve that.
Fixes #701.
> backend: late import of ldap module

- whoisd/nipap-whoisd
- whoisd/whoisd.conf.dist
SocketServer is hard-coded to listen to IPv4 so this introduces some
monkey patching to get around that and enable it for listening on an
IPv6 socket. When binding to "" or :: the server will listen on both
IPv4 and IPv6. To listen on an IPv4 address it needs to be specified as
an IPv4-mapped IPv6 address.
Fixes #718.
> whoisd: add IPv6 support

- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
Adds the cacert and tls options to LdapAuth.
cacert should be the full path to the cacert used on the LDAP server
tls should be a truthful value (non-zero) to force TLS
Also fixed a bug with the global name ldap not being available
> More additional LDAP support

- nipap/debian/nipapd.init
- whoisd/debian/init
Previously, the init scripts would unconditionally return 0 when called
with the "status" action, which misleads (non-human) callers into
believing that the service in question is running even though it is not.
Fix that by explicitly exiting the init script with the appropriate
return code. Also change the slightly improper usage of log_action_msg
with log_success_msg/log_failure_msg.
> Make "status" action of init scripts LSB compliant

- nipap/nipap.conf.dist
Replace 'test.com' with 'example.com'.
The examples for how to configure LDAP, in particular the basedn was not
particularly clear since it didn't include ou=Users, which is typically
used.
> Update config examples for LDAP

- .travis.yml
- nipap-cli/nipap
- nipap-cli/nipap.man.rst
- nipap-www/debian/postinst
- nipap/nipap-passwd
- nipap/nipap-passwd.man.rst
- nipap/nipapd
* Since version 2.7 optparse is deprecated and replaced by argparse. This patch replaces optparse in the given files.
* Also added a small note in nipap.man.rst relating to the settings file.
* In the nipap-passwd tool you can now list a specific user (with option -u).
> Replace optparse with argparse

- nipap-www/nipapwww/controllers/xhr.py
- nipap-www/nipapwww/public/controllers.js
There were two issues surrounding the handling of positive infinite
values for the expires field. Upon reading the values the JSON encoder
would always cast to string which doesn't work very well with None
values as that would be represented as the string "None" rather that
<nil> over the wire and as we use nil for presenting infinity, this
would mess things up. Properly handling this means the text input in the
web form stays empty.
Secondly, we mangle the expires field to format the field into a ISO8601
value before sending to the backend when editing/adding a prefix. We
shouldn't mangle if the expires field is empty, since this means
infinity and mangling it will mess it up.
Fixes #721.
> www: fix expires field of infinity

- nipap/sql/triggers.plsql
- tests/nipaptest.py
The last_modified value was in fact not updated when modifying a prefix, in most cases at least. This was due to conditions on the trigger that performs the update making it run only when the vrf_id, type or prefix was changed. The conditions themselves are there to increase performance by avoiding to run a large trigger function when it's not necessary.
By moving the conditional part from the trigger definition into the trigger function, the last_modified value can always be updated but the lions share of the function avoided when it is not needed.
> Fix updating of the last_modified value

- nipap-cli/nipap_cli/nipap_cli.py
- nipap-www/nipapwww/public/nipap.js
- nipap/nipap/backend.py
- tests/nipaptest.py
- tests/xmlrpc.py
This changes the query interpretation format to a new and improved format that is able to correctly model a query. The old format is a list with an entry for each element, which doesn't allow correctly grouping a more complex query.
For example, the query 'a b c' means we have three elements; a, b and c. There is an implicit boolean AND operator between them and so the query interpretation could be correctly represented with just a list and an implicit AND operator. However, as we wish to support a query like 'a AND (b or c)' we now have a different operator and it is (explicitly) grouped in a way that isn't possible to express with a flat list. The new format follows the query format, ie it is a hierarchy and the new query interpretation format can thus express all possible queries.
> Improve query interpretation format

- nipap-www/nipapwww/public/directives.js
- nipap-www/nipapwww/public/templates/pool_selector_popup.html
When adding a prefix, the pool it is a member of can be specified,
however the page didn't allow you to deselect the pool once it was
selected. That is now fixed.
Fixes #732.
> www: allow deselection of selected pool

- nipap-www/nipapwww/public/templates/pool_list.html
- nipap-www/nipapwww/public/templates/vrf_list.html
- nipap-www/nipapwww/templates/macros.html
This sets the focus on the search input on page load for the VRF and
pool page and aligns the attribute for the prefix list page.
Fixes #744.
> www: autofocus on search input field

- nipap-www/nipapwww/public/templates/pool_selector_popup.html
- nipap-www/nipapwww/public/templates/vrf_selector.html
The VRF and pool selector would close when clicked on which isn't very
intuitive at all. Found a stackoverflow discussion on this topic:
http://stackoverflow.com/questions/23698316/how-to-prevent-an-angular-bootstrap-dropdown-from-closing-unbind-event-which-wa
This implements that fix for both VRF and pool selector.
Fixes #728.
> www: fix incorrect close of vrf and pool selector

- nipap/nipapd
Psutil.error is an internal class and shouldn't be referenced from
outside as per https://code.google.com/p/psutil/issues/detail?id=246
Fixes #760
> Fix usage of psutil

- nipap/sql/triggers.plsql
- tests/nipaptest.py
IP:id formatted VRF RT values are validated so we make sure that the IP part is actually a well formed IPv4 address and not just a bunch of characters separated by dots. The old code would however, incorrectly, save the integer representation of the IPv4 address instead of its dotted quad notation which is usually what the user wants :)
Also adds a test case
> Fix for VRF RT formatted as IP:id

- nipap-cli/debian/control
- nipap-cli/nipap_cli/nipap_cli.py
- nipap-cli/setup.py
Previously the view prefix function wouldn't accept the display_prefix,
i.e. a prefix with its natural mask. To show a host prefix it had to be
entered either with a host mask, e.g. /32 or /128 or with no mask at all.
There are scenarios when a host has the network address, most typically
when using /31 or /127 networks. To distinguish between the two, the
mask must be entered, i.e. use /31 to show the network or /32 to show
the host.
Fixes #738.
I did contemplate putting in a warning and/or hint saying that users
need to be careful when using a network address since it could
potentially hide a host prefix but decided not too as ultimately users
should know what they are doing.  I think we should add a section to the
NIPAP user guide CLI section about this thoug.
This also introduces a …
> cli: accept natural mask for prefix view

- nipap-www/debian/postinst
The regexp that extracts the username assumed that the username always
contain a '@' character, like web-user@local. It would fail hard if it
didn't.
Fixes #775.
> www: fix debian postinst script

- nipap/nipap/backend.py
Add a global list of all attributes of a prefix, also marking which ones
are read-only or read-write, which we derive a second list from that
only contains the writable attributes.
These two lists are then used in all the places where we check input
arguments.
Fixes #667.
@garberg, what do you think of this approach? I didn't apply the same
for pools and VRFs because I wanted input on this one first but if you
think this looks good we should do the same for them as well.
> backend: update allowed attributes for prefix spec

- nipap/nipap/backend.py
This implements the equivalent of what was done in
93fbf8de6b598cd4e22568e7c3c59df04a60b5c8 but for pools. Instead of
spreading out a list of attributes in various places we keep one global
list which we reference. Neater code!
Fixes #784.
> backend: rework attribute list for pool

- nipap/nipap/backend.py
This implements the equivalent of what was done in
93fbf8de6b598cd4e22568e7c3c59df04a60b5c8 but for VRFs. Instead of
spreading out a list of attributes in various places we keep one global
list which we reference. Neater code!
Fixes #785.
> backend: rework attribute list for VRF

- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
Added functionality to allow NIPAP administrators to specify separate
LDAP credentials used when performing the LDAP search for the user
logging in. This is needed for LDAP setups where ordinary user accounts
are not permitted to search the LDAP database.
The search for the user logging in is performed after the user has been
authenticated to get full name and permissions (if used).
Fixes #794
> authlib: Separate LDAP search credentials

- pynipap/setup.py
xmlrpclib is shipped with Python so I don't think we need to declare a
dependency on it.
Fixes #805.
> pynipap: remove xmlrpc dependency

- nipap-cli/nipap_cli/nipap_cli.py
- tests/nipaptest.py
The logic to automatically guess type of a new prefix failed when trying
to add a prefix larger than one already existing but with the same
network mask as the search to find the parent prefix would ignore the
prefix length. This is now fixed!
For example, 10.0.0.0/24 is an assignment and we are trying to add
10.0.0.0/8 as a reservation. The auto type guess would strip away the
prefix length, resulting in a search for "10.0.0.0" which the backend
interprets as 10.0.0.0/32 and that returns 10.0.0.0/24 as the parent
prefix. Since 10.0.0.0/24 is an assignment, the type would be changed to
"host" and the new prefix would be created with a /32 mask.
Now we check if there are bits set to the right of the mask and only
then do we assume a /32, otherwise we search with the prefix length. …
> cli: fix prefix type guessing

- utilities/export-isc-dhcp.template
- utilities/export-template.py
This adds a generic export script that can be used for producing various
configuration files based on data from NIPAP.
In addition to the script, I have provided a basic template for ISC DHCP
config (not tested).
Fixes #815.
> Add generic export script based on template

- utilities/boilerplate.py
The default arguments in the argument parser prevents the use of the
values from the configuration file.
Fixes #821.
> Remove default arguments in boilerplate

- utilities/bulk-string-replace.py
Added a script which can be used to "rename" prefixes in NIPAP, that is change description and node, in bulk. When executed, the script will display a list of the prefixes to change and what they will be changed to as well as let the user select what prefixes to perform the operation on.  Either all, a few selected prefixes or all prefixes EXCEPT the selected prefixes can be chosen.
> utilities: Added script to bulk rename prefixes

- nipap-cli/nipap
- nipap-cli/nipap_cli/nipap_cli.py
- nipap-cli/nipaprc
The output columns for 'nipap address list' can now be specified with
the -c/--columns paramter, which takes a comma separated list of column
names. To append columns to the default columns, prefix the list with a
"+".
Specify custom columns:
kll@lingloi320 ~ $ nipap address list -c prefix
Searching for prefixes in any VRF...
Prefix
===============================
1.0.0.0/8
1.0.0.0/16
1.0.0.0/24
1.0.0.128/25
2001:db8:1:1::/64
Append the free_addresses to the default set of columns:
kll@lingloi320 ~ $ nipap address list -c +used_addresses,free_addresses
Searching for prefixes in any VRF...
VRF RT         Prefix                           #  Node   Order ID  Customer ID  Description  Used addresses  Free addresses
=============================================================================== …
> cli: add customisable output columns

- whoisd/nipap-whoisd
This adds Unicode support for whoisd by decoding requests using IDNA and/or UTF-8.
Responses are now sent in UTF-8.
Not sure if we should merge this on 0.28 or wait for 0.29.
Fixes #808.
> Unicode support for whoisd

- nipap-cli/helper-nipap
There are cases, such as when .nipaprc doesn't exist, that prevents
helper-nipap to work completely. Suppressing any such error message
seems to be the only reasonable option and therefore I've modified this
try/except clause to match all exceptions.
Fixes #711.
> Catch all exceptions to suppress error messages

- nipap-cli/nipap
This is really rather weird but raw_input has an issue with UTF-8 output
even when stdout encoding is already set to UTF-8. Forcing UTF-8 for
UTF-8 terminals, which really should be a no-op, fixes that issue.
Since we are checking for UTF-8 output, this should be compatible with
legacy terminals.
Redirected or piped output is forced to UTF-8 just as before.
Fixes #841.
> cli: force UTF-8 output on UTF-8 terminals

- nipap/nipap/backend.py
We would get an exception when 0 objects were updated by a query due to
a bug in this code which is now being handled.
Fixes #843.
> nipapd: fix 0 update

- nipap-cli/helper-nipap
Tab completion for anything that required fetching data from the backend
didn't work. I don't understand how it ever did as there's no code to
set up the XML-RPC connection.
This adds some code, more or less copied from the CLI. We don't check
the permissions like we do in the CLI, but I figure the user will get a
warning about that soon enough anyway.
> cli: Fix XML-RPC connection for helper-nipap

- nipap/nipap/backend.py
This enables search based on prefix-length as a match. It's using the
masklen() function in Postgres to do this and there is currently no
functional index on that so it might be slow.
Fixes #847.
> nipapd: enable search on prefix-length

- .travis.yml
This updates the Travis config to use Travis GCE build environment instead of the legacy environment we have been using up till now.
A few changes are required to the installation process for this.
> Use Travis GCE & Ubuntu 14.04 for build

- docs/config-www.rst
Apache 2.4 need a bit more configuration around permissions to get
things going.
Fixes #796.
> Add instructions for configuring Apache 2.4

- .travis.yml
- docs/install-debian.rst
- nipap/debian/control
This removes the dependency on postgres from the nipapd package, allowing postgres to be installed on another machine. In addition nipapd can now be installed on the latest versions of Ubuntu as they have a newer postgresql version than we specified in our control file.
> drop postgres dep

- docs/sphinx/conf.py
- nipap/nipap/backend.py
- pynipap/pynipap.py
Allright, I managed to bust up the original PR for this, #758, so here's a new one. I've added explanations regarding the mapping of functions in pynipap to backend functions to each reference. During offline discussions we debated whether the references should be to the XML-RPC functions or all the way to the backend functions, but from what I remember we agreed on referring to the backend (as that's where the information of interest actually is available), even though there is an XML-RPC layer in between.
Original message:
To avoid duplicating information the pynipap documentation is very brief as most data is passed straight to the backend anyway. This PR tries to make this more clear by adding references to the corresponding backend function to each of the pynipap class methods which …
> Add references to backend functions in pynipap docs

- nipap/nipap/xmlrpc.py
Fix of two bugs in how extra_query was handled:
* ```smart_search_pool``` - handle queries without extra_query set
* ```smart_search_asn``` - pass extra_query to internal backend function
> Handle extra_query in smart_search_pool and smart_search_asn

- nipap/nipap-passwd
```
[root@nipap nipap-www]# nipap-passwd test-user -u cli -p cli
Traceback (most recent call last):
File "/sbin/nipap-passwd", line 71, in <module>
auth = af.get_auth(options.username, options.password, "nipap", {})
NameError: name 'options' is not defined
```
> fix: NameError: name 'options' is not defined

- nipap/nipap/authlib.py
Replicate functionality from add_user function. We can't just update the
password like any other column since we have to salt+hash it first...
Fixes #931.
> Fix changing user password using nipap-passwd

- nipap/nipap/authlib.py
Decode the full name string returned from the LDAP server as UTF-8.
Something similar is needed for the group names as well. I have some code to fix this, but unfortunately not the means to test it ATM.
> authlib: Handle international chars in full name

- nipap-www/debian/postinst
This fixes the issue where each subsequent install of the nipap-www package would append a "@local" to the XML-RPC URI in nipap.conf
> Fix regexp in install of nipap-www

- nipap-www/nipapwww/public/nipap.js
- nipap/nipap/backend.py
For certain queries, like when expanding a prefix by clicking the '+' in
the web UI we really shouldn't have a limit. Unlimited is signified by
setting max_result to False or None.
Downside might be DoS attack on the backend or some incorrect logic
somewhere blowing it up with heavy queries inadvertently.
Fixes #466.
> Support unlimited max_result for search_prefix

- whoisd/nipap-whoisd
Allow running in the foreground.
Shut down cleanly.
Also avoid the error message around address already in use through
address reuse.
Fixes #920.
> whoisd: enable foreground mode

- nipap/nipap/smart_parsing.py
- tests/nipaptest.py
The backend smart parsing function currently builds broken queries for stuff that looks like a VRF RT, like '123:456'. This fixes that and adds a test case to make sure we catch this in the future.
> Fix broken parsing of VRF RT

- nipap-cli/nipap
- nipap-cli/nipap_cli/nipap_cli.py
In addition to reading the connection parameters from the .nipaprc
configuration file we now also try to get them from environment
variables. We prefer environment variables, then from .nipaprc and last,
in the case of the password, we will interactively prompt for it.
nipapd host and port now also have the defaults 'localhost' and 1337
respectively.
Fixes #838.
> cli: read connection params from env or prompt

- nipap/xml-test.py
- nipap/xmlbench.py
- tests/performance/speedtest.py
- utilities/boilerplate.py
- utilities/export-csv.py
- utilities/export-template.py
- utilities/remove-all.py
- utilities/text-import.py
argparse is the modern alternative and the recommended lib for parsing command line arguments. I think optparse isn't even in py3.
All these changes are written blind - I haven't tested anything but I actually think that should be fine =) Easy to fix if anything should pop up.
Part of #747.
> Use argparse instead of optparse

- .travis.yml
- nipap/debian/nipapd.postinst
- nipap/nipap.conf.dist
I've switched out some of the values that we want to substitue to Jinja2
style variables so that it's easier to use, well, Jinja2 to do the
rendering of the config file.
This is kind of preparatory work for putting nipapd in a docker
container as I envision using envtpl to do the variable subsitution.
The debian nipapd postinst script is however still using sed since I
didn't want to include envtpl in the normal debian package and I'm too
lazy to write a Jinja2 renderer right now. This should still be better
than before IMHO.
Fixes #949.
> backend: switch nipap.conf.dist to Jinja2 syntax

- nipap/nipap/smart_parsing.py
- tests/nipaptest.py
The new smart parser that I wrote didn't correctly parse IPv6 addresses,
instead mistaking them for VRF RTs, which are also colon separated
numbers. We didn't have a test case for this and I believe I didn't
catch this earlier as I probably use the Tele2 IPv6 prefix 2a00:db8::/25
that contains hexadecimal characters, thus differing from a VRF RT.
I have now added the explicit classes ipv6_address and ipv6_prefix which
also lead to their own expansion from AST to dictsql.
There are now also test cases to cover shortened IPv4 prefixes (like
10.0/8) and IPv4 prefixes with bits set in host part so we check that
the strict prefix mangling works.
Fixes #954.
> backend: fix smart parsing of IPv6 prefixes

- Dockerfile.nipapd
This should reduce the size of the resulting docker image slightly as
well as removing unecessary layers.
> docker nipapd: Clean up after apt

- nipap-cli/debian/control
- nipap-www/debian/control
- pynipap/debian/control
Bumped the Python dependency from 2.4 (which probably cannot even run the relevant code) to 2.7. I've previously pushed for 2.6, but f*ckit. Debian has been shipped with 2.7 since wheezy, which was released in May 2013.
Also changed the Python dependency in the pynipap package to a specific version to avoid letting the resulting dependency vary with the build system.
> Bump Python dependency to 2.7

- nipap/nipap/smart_parsing.py
Added the prefix_length field to the prefix smart parser module.
Fixes #973
> backend: Add prefix_length to prefix smart parser

- nipap/nipap/backend.py
- tests/nipaptest.py
Update the format of the result returned when the smart parser encounters a ValueError to match the usual result dict. I chose to add some empty values as well, to simplify client implementation.
Result from the CLI client:
```
$ ./nipap --show-interpretation a l 'foo "'
Searching for prefixes in any VRF...
Query interpretation:
`-- foo ": unclosed quote, please close quote!
This is not a proper search term as it contains en uneven amount of quotes.
No addresses matching 'foo "' found.
```
Fixes #982
> Correct response on smart parser error

- nipap-www/nipapwww/public/nipap.js
The VRF filter (list of currently selected VRFs which is used as an additional search filter for the prefix searches) was not modified for the new smart search interpretation format.
The change introduced relies on that the search result returned refers to the search string currently entered. This is not always the case as the user can change the query string while the response is received. For this case, when we need to figure out whether the query was empty so we can append the selected VRFs to the list, this is not a problem, but it strikes me that it might be beneficial to add the full query string to the result as well? Now only the parsed, sliced and diced version is returned in the interpretation.
> Handle new interpretation format in VRF filter

- pynipap/pynipap.py
My previously added notes, in PR #991, were missing some necessary markup causing
sphinx to render the notes incorrectly. Correcting this.
I've tested this with a local sphinx-build and it appears correctly now.
> Correcting Sphinx Markup in pynipap.py

- nso-nipap/nso-nipap/src/java/src/net/spritelink/nsonipap/ConfigCdbSub.java
Continue with the next request when an error occurs in the allocation of prefixes. Before this change, NSO would lock up when for example trying to allocate prefixes from a pool without free prefixes.
> Continue on error

- nso-nipap/nso-nipap/src/java/src/net/spritelink/nsonipap/ConfigCdbSub.java
Obviously something just went too fast. The changes to how redeploys are performed which I committed are broken (a part of the redeploy path from the example I copied wasn't removed which resulted in an incorrect redeploy path).
This PR addresses that issue.
> Correct redeploy path

- nipap-cli/debian/rules
With the introduction of the pybuild build system, python3 packages not either being named python3-* or depending on ${python3:Depends} gets their modules installed in a python version specific directory (in my case /usr/lib/python3.5/dist-packages). This is not very suitable for a package which should be possible to run with different versions of python3.
The fix implemented is to simply tell the python setup script to install the packages into a non version specific directory, in this case /usr/lib/python3/dist-packages. A bit of a hackish solution, but given
how pybuild works I found no cleaner solution.
Fixes #1003
> Fix installation path of CLI

- nipap-www/nipapwww/controllers/xhr.py
The "top-level" error flag newly introduced in the smart_search_-functions collided with an error flag used by the web interface. This is a quick fix for that issue which simply removes the error key from the result received from smart_search. The flag is currently only used to signal query string parser errors, which also are present deeper in the interpretation dict where it will be picked up and displayed by the web UI. Thus no functionality is lost when the top-level flag is removed.
I was probably a bit too quick implementing the error flag; we should probably think through how to convey "soft errors" (such as string parsing errors) vs "hard errors" (such as, for example, the backend
being unable to reach the database) and how to do it in a future JSON-based REST API.
Fixes #1004.
> www: Handle top-level error flag from smart_search

- Dockerfile.www
- nipap-www/entrypoint.sh
- nipap/entrypoint.sh
- nipap/nipap.conf.dist
Added a dockerfile and entrypoint-script for nipap-www. It's based on a standard ubuntu:xenial-image, serving the NIPAP web UI with apache2 with mod_wsgi.
All installation of dependencies and NIPAP packages is done in the dockerfile, while the local auth database is setup, permissions are corrected and apache2 configured in the entrypoint shell script. The
dockerfile currently doesn't provide any way to make changes to the nipap-www.ini-file.
> Dockerify nipap-www

- nipap-cli/nipap_cli/nipap_cli.py
- nipap-www/nipapwww/public/nipap.js
- nipap/nipap/smart_parsing.py
- tests/nipaptest.py
Fix prefix smart search where the search string contains tags and adjust debug logging statements to display the correct value.
Also adjusted how the search interpretation is displayed slightly.
Before:
```#foo: tag must contain #foo``` - a bit misleading as the tag name in this case actually is ```foo```, without hash.
After:
```#foo: tag must contain foo``` - correct as the tag name is ```foo```.
Fixes #1008.
> Fix prefix smart search with tags

- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/templates/pool_form.html
- nipap-www/nipapwww/public/templates/prefix_form.html
- nipap-www/nipapwww/public/templates/vrf_form.html
In the web UI, improve the handling of extra attributes with empty values so that:
* Entries where both the attribute and value is empty are removed when sending data to the server.
* The attribute field is mandatory when a value is entered.
Fixes #882.
> Improve handling of extra attributes with empty values

- docs/install-unix.rst
Just to have this in the docs, worked on CentOS 7 
https://github.com/SpriteLink/NIPAP/issues/802
> Docs - Initialize SQLite auth database

- nipap/nipap/smart_parsing.py
This mangles IPv4 address in search queries through IPy to get a
properly formatted IPv4 address before we send it to Postgres. We do
validation of IPv4 addresses but once they are verified we send the
original value, so for example 10.18.01.1 is recognized as IPv4 but
Postgres doesn't like the leading 0 in the third octet. By running it
through IPy we get rid of that leading 0 and all is fine.
Fixes #860.
> nipapd: mangle IPv4 address

- nipap-www/debian/source/options
Update extend-diff-ignore for the nipap-www debian package to ignore last additions: requirements.txt and entrypoint.txt.
> www: Update extend-diff-ignore

- nipap-www/nipapwww/public/nipap.js
After the AngularJS upgrade from v1.3.15 to v1.5.3 a slash has been introduced in the URI from some reason. The code in NIPAP which stores the current search state in the URI neeed to be updated to reflect this, to avoid the page from reloading when opening the VRF selector.
Fixes #1029.
> www: Add slash to generated URI

- nipap-cli/nipap_cli/command.py
- nipap-www/nipapwww/controllers/prefix.py
- nipap/nipap/backend.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Use `is` or `is not` to compare with `None`](https://www.quantifiedcode.com/app/issue_class/3IY8CZ0v)
Issue details: [https://www.quantifiedcode.com/app/project/gh:SpriteLink:NIPAP?groups=code_patterns/%3A3IY8CZ0v](https://www.quantifiedcode.com/app/project/gh:SpriteLink:NIPAP?groups=code_patterns/%3A3IY8CZ0v)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Use `is` or `is not` to compare with `None`" issue

- .landscape.yml
landscape.io doesn't correctly run it checks and I'm tired of fiddling
around with it. Rather stick to QuantifiedCode and HoundCI for the time
being, thus removing the Landscape.io config file.
> Remove landscape config file

- nipap/nipap/backend.py
It won't do anything but at least we avoid throwing an exception. This
can be useful if someone wants to feed the search_options returned by a
query into another query.
Fixes #998.
> Accept parent_prefix as None

- nipap/nipap/backend.py
Update the code which catches invalid input syntax for types to handle other types than cidr/inet. Duplicate of #1046, which one should we use? :smile:
> backend: Catch invalid input syntax for more types

- nipap/nipap/smart_parsing.py
- nipap/sql/Makefile
- tests/nipaptest.py
Update the smart parser to match tags against a prefix's inherited as well as "own" tags.
Fixes #1055.
> Match inherited tags

- nipap-www/debian/control
The request.json attribute wich is used to extract the JSON data which is POST:ed to the web server was not available until WebOb 1.2.0. Thus, adding an explicit dependency on this or greater versions.
Fixes #1066.
> Explicitly depend on python-webob >= 1.2

- nipap/nipap/backend.py
- nipap/nipap/xmlrpc.py
Added documentation of the `recursive` option to the remove_prefix function.
> Document recursive prefix remove

- jnipap/JnipapTester.java
- jnipap/jnipap/AuthFailedException.java
- jnipap/jnipap/ConnectionException.java
- jnipap/jnipap/DuplicateException.java
- jnipap/jnipap/InvalidParameterException.java
- jnipap/jnipap/MissingInputException.java
- jnipap/jnipap/NonExistentException.java
- jnipap/jnipap/Prefix.java
- jnipap/jnipap/ValueException.java
Added support for recursive prefix remove to jnipap, including a simple test case. The feature was added by overloading the previously existing remove()-function, so the old API is still intact and the change shouldn't break old code using the library.
> Add support for recursive prefix remove

- docs/INSTALL.rst
Users should always rely on `apt-get dist-upgrade` rather than `apt-get upgrade` so as to make sure we pull in the latest dependencies.
> Add upgrade instructions

- nipap/nipapd
With the change from optparse to argparse, the override of configuration parameters from the config file with CLI arguments stopped working. This was due to argparse assigning the default value "False" to arguments with action store_true, while optparse assigned None. This was fixed by explicitly setting the default value to None.
Also did some cleanup of the code where the override is performed.
Fixes #1044
> nipapd: Fix override of configuration params

- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/services.js
For integers, rewrite empty string with null values and strip whitespace. For strings these type of actions are performed server-side, but as the long-term goal is to move functionality from server to client-side I chose to put this code there.
Fixes #1085
> Replace empty string with null

- nipap/nipap/backend.py
Heh, can't check len(params) == 0 when we set it on the line above,
guaranteeing it will always be at least 1...
Fixes #1091.
> Fix list_prefix with family arg

- nipap-www/nipapwww/public/nipap.js
Don't show the "Add prefix from prefix"-option in the prefix list popup menu when clicking prefixes with max prefix length, as no prefixes can be allocated from these.
Fixes #863
> Only show add-prefix-from-prefix option when it's usable

- nipap/nipap/backend.py
from-prefix consumes list of prefixes rather than single prefix. Docstring does not reflect this
> "from-prefix" docstring fix

- nipap-www/nipapwww/controllers/xhr.py
Since the change from sending data from the client to the server side of the web UI with a POST containing JSON data, the handling of the monitor attribute has been broken in the web UI. The broken behaviour lead to it not only being impossible to change the monitor attribute from the web UI, but that it was disabled whenever updating a prefix in the web UI.
Fixes #1130
> Fix handling of monitor-attribute

- nipap-www/nipapwww/templates/prefix_list.html
Since the last upgrade of AngularJS, the part of the URL to the right of the hash has been prefixed with a slash. The library used to parse the URL considers the slash as part of the name of the parameter and thus the name needs to be updated when accessing it.
With this change, the URL is again successfully parsed.
This is a hack to re-enable the functionality lost with the AngularJS upgrade. This will all be replaced with an AngularJS implementation of the prefix list page.
Fixes #1115
Fixes #1089
> Re-enable parsing of query string in URL

- nipap-cli/nipap
Should help with https://github.com/SpriteLink/NIPAP/issues/1116
Example error
`
(nipap)➜  nipap-cli git:(barisa/cli) ✗ ./nipap
Failed to read file, make sure file /Users/barisa/.nipaprc is readable by current user
`
> Give nice error message if nipaprc isn't readable by the user

- docs/config-www.rst
Hi,
There's typo [here in the documentation](http://spritelink.github.io/NIPAP/docs/config-www.html). The password is "s3cr3t" in the first command and it becomes "s3cret" in the second one. 
Thanks,
Ben
> Fix typo in password example in documentation

- .travis.yml
The CI build image is now shipped with PostgreSQL 9.2 pre-installed. Updated the install phase to match this.
> Update CI install phase to install PostgreSQL 9.2

- nipap-www/nipapwww/public/nipap.js
Users have reported the delay from typing a character to a search being performed is too short. Increasing from 200 to 500 ms.
Fixes #1208
> Increase search delay to 500 ms

- nipap-www/nipapwww/public/templates/prefix_form.html
Fixes a bug where the last extra attribute added to a prefix would be removed, no matter which one was clicked.
Fixes #1205
> Fixed removal of extra attributes

- NEWS
- nipap-cli/debian/changelog
- nipap-cli/nipap_cli/__init__.py
- nipap-www/debian/changelog
- nipap-www/nipap_www.egg-info/PKG-INFO
- nipap-www/nipap_www.egg-info/requires.txt
- nipap-www/nipapwww/__init__.py
- nipap/debian/changelog
- nipap/nipap/__init__.py
- pynipap/debian/changelog
- pynipap/pynipap.py
- whoisd/debian/changelog
- whoisd/nipap_whoisd.py
> Release v0.29.8

- pynipap/pynipap.py
The example shows importing pynipap and directly importing some names like VRF,
Prefix and Pool but AuthOption is not among them so we would need to refer to it
as pynipap.AuthOption. It's important we are consistent in our documentation.
> Fix path for AuthOptions

- README.md
Update Travis-CI barge URL after move from travis-ci.org to travis-ci.com.
> Update Travis-CI badge after move

- nipap/requirements.txt
Bump to Werkzeug 0.16.1. Replaces #1232 which suggests 0.15.3 which has a bug with Python 2.7.5.
> Bump Werkzeug dependency to 0.16.1

- nipap-cli/nipap
It seems that newer python versions (I'm on python 3.8) do not accept
`None` by default. Adding the `allow_no_value` argument fixes that.
> fix(nipap-cli): Allow `None` as ConfigParser values

- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/templates/vrf_list.html
- nipap/nipap/xmlrpc.py
Althoug the smart search functionality was implemented, the VRF list page still performed a slow bulk-load of all VRFs. Replaces this with an initial smart search query which matches any VRF and returns the 50 first entries to begin populating the list.
Also disabled infinite-scroll while data is fetched to avoid bursting requests when reaching the end of the page, added a loading indicator and stopped the infinity scroll when all VRFs has been fetched.
> Improvements of VRF list smart search

- nipap/nipap/xmlrpc.py
Added a try/except around import Flask-Compress, trying the old style if the new style does not work.
> Fallback to old Flask-Compress import

- nipap-cli/debian/postinst
Use GNU coreutils `install` to install bash completion script, to make sure that the directory exists before copying the file.
Fixes #1248, #1241
> Use `install` to install bash completion script

- .travis.yml
- nipap/debian/control
- nipap/nipap.conf.dist
- nipap/nipap/rest.py
- nipap/nipap/xmlrpc.py
- nipap/nipapd
- nipap/requirements.txt
- tests/test_rest.py
Adding some REST functionality to NIPAP.
The change will make it possible to do XMLRPC and REST requests to the same IP and Port.
Per this pull request only the following NIPAP functions are provided by the REST API:
- list_prefix
- add_prefix
- remove_prefix
The above are done through GET, POST and DELETE to the endpoint /rest/v1/prefixes
PUT needs to be added for editing prefixes, it's not with this PR.
Further development should be made to add the other functionalities that are in the XMLRPC API.
This should/might be done by adding more classes in rest.py
> Adding REST API feature

- docs/install-debian.rst
I added the `sudo` commands to the copy-pastable parts of the directions, just to make it a little easier for people to install everything. Sometimes, some new people to linux might not yet have the `sudo` requirement linked in their heads, so this just removes that barrier.
> Updated Code-Based Directions

- nipap/nipap/xmlrpc.py
When NIPAP page rendering was slow we found that removing this sleep
wastly improved performance. It was introduced with commit 1da02003
(www: Improvements of VRF list smart search).
> nipapd: improve smart_search_vrf search

- .github/workflows/ci.yml
- nipap/nipap/rest.py
- nipap/nipapd
- tests/test_rest.py
Some fixes for #1310.
Added support for case insensitive search for string data values in the REST API + added some new tests for the REST API.
Also improved the error handling a bit so that the error message is returned correctly.
> REST API case-insensitive search - fixes

- nipap/nipapd
Clean up residual stuff from development. In fact setting this hashbang might be something we really want to do, but it needs to be thought through properly.
> Remove accidental python2 hashbang

- nipap-www/nipapwww/xhr.py
I got this exception for several versions now:
```
ERROR in app: Exception on /xhr/smart_search_prefix [POST]
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File …
```
> www: Fix KeyError in xhr.py

- nipap/nipap/backend.py
Fixed a bug in the backend where the edit_prefix operation would fail for prefixes in a VRF where the VRF wasn't included in the prefix attributes.
> Handle edit_prefix without VRF

- nipap/nipap/smart_parsing.py
- nipap/nipap/xmlrpc.py
- nipap/xmlbench.py
- tests/test_cli.py
- tests/test_rest.py
- tests/test_xmlrpc.py
- whoisd/nipap_whoisd.py
> Misc style fixes

- nipap/nipap.conf.dist
The config variable for configuring forks in the distributed nipap.conf was erroneous (!).
Fixes #1171
> Correct config variable for forks

- nipap-cli/nipap_cli/nipap_cli.py
An annoying little bug when you use # in your password.
Using the password "MySecretPassword#2023"
```
$ nipap address list 123.123.123.124
Searching for prefixes in any VRF...
Traceback (most recent call last):
File "/usr/lib/python3.11/http/client.py", line 889, in _get_hostport
port = int(host[i+1:])
^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'MySecretPassword'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/nipap/bin/nipap", line 133, in <module>
cmd.exe(cmd.arg, cmd.exe_options, args)
File "/opt/nipap/lib/python3.11/site-packages/nipap_cli/nipap_cli.py", line 588, in list_prefix
res = Prefix.smart_search(search_string, { 'parents_depth': -1, …
```
> UrlLib.Parse.Quote on password else it breaks on #

- nipap/nipap/authlib.py
It seems the Python 3 version of the LDAP module returns bytes instead of strings. This caused the full name fetched from LDAP, now a bytes object, to be passed around and sent to the backend as an xmlrpc.client.Binary from the web UI and causing a crash.
Updated the LdapAuth class to decode the received full name and encode strings to bytes before determining group membership.
> Handle binary data from LDAP

- .github/workflows/ci.yml
The upgrade tests were disabled as we couldn't install both Python 2 and Python 3 versions on the test runner image. Now that the Python 3 version of NIPAP is released, the upgrade testa can be re-enabled.
> Re-enable upgrade tests

- .github/workflows/ci.yml
- pynipap/debian/control
- pynipap/debian/rules
- pynipap/pynipap.py
- pynipap/setup.py
As all NIPAP components now are Python 3, let's finally drop Python 2 support for pynipap to simplify project maintenance.
> Drop Python 2 support in pynipap

- nipap-cli/nipap
- nipap-cli/nipaprc
- nipap-www/nipapwww/__init__.py
- nipap-www/nipapwww/tracing.py
- nipap-www/nipapwww/xhr.py
- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
- nipap/nipap/backend.py
- nipap/nipap/rest.py
- nipap/nipap/tracing.py
- nipap/nipapd
- nipap/requirements.txt
- pynipap/pynipap.py
- pynipap/setup.py
- pynipap/tracing.py
Add OpenTelemetry tracing for cli, www and nipapd
> Add OpenTelemetry tracing

- nipap-www/nipapwww/__init__.py
The init_tracing function referred to when initializing tracing in the web UI should be imported from the common NIPAP tracing module.
> Correct import path for init_tracing

- pynipap/pynipap.py
- pynipap/tracing.py
The implementation of OpenTelemetry tracing broke TLS support in pynipap. Fix.
> Fix TLS support after tracing feature

- docs/release-handling.rst
- nipap-www/entrypoint.sh
Two smaller fixes related to Docker packaging:
* Added documentation about the repos and release handling
* Auto-generate WWW secret key if missing when starting up nipap-www container
> Added Docker docs, auto-generate secret key

- nipap/nipap/authlib.py
The LDAP auth backend never explicitly closed the connection to the LDAP server, when meant that it was kept open until the auth object timed out from the auth cache which can take some time.
Now LDAP connections are closed once the authentication is done.
> nipapd: Close LDAP connection after authentication

- Dockerfile.nipapd
- Dockerfile.www
Fix the handling of CA certificates in Dockerfile.nipapd - the previous implementation simply didn't work as the Dockerfile COPY command only copies directory content and not the directory itself.
Also added the same handling to Dockerfile.www.
> Fix handling of CA certificates in Dockerfile

- nipap/nipap/tracing.py
- nipap/nipapd
Fix the tracing proxy function by removing the Host header from the headers received from tracing client before POST:ing it to the tracing receiver.
Improve logging of how the setup of tracing is progressing.
> Fix trace proxy, improve logs

- nipap-cli/nipap
Proxying traces via nipapd over TLS now works.
> Fix proxying of traces over TLS in CLI

- .github/workflows/ci.yml
- Dockerfile.nipapd
- nipap/sql/Makefile
Added run of test suite towards containerized nipapd and push of images to Github when merging or pushing to master.
> Docker tests and push

- nipap-cli/nipap
Added the possibility to add global run-time configuration to the NIPAP CLI in /etc/nipaprc. The global file, if exists, will be read first and any option set in the local ~/.nipaprc file will override what's set in the global file.
> Read global configuration in CLI

- nipap-cli/nipap
There was a typo causing the default config for port being missing.
> Fixed default config for port in CLI

- nipap/nipapd
Since forever nipapd have avoided to fork multiple processes when running in forground. I think the idea was to simplify debugging etc, never to be used in production. However, when deploying nipapd as a Docker container the process is running is foreground by default also in production and thus the behaviour is now changed to fork also for that case.
> Fork also when running in foreground

- nipap-cli/nipap_cli/nipap_cli.py
- nipap/nipap/authlib.py
The read-only group name validation was missing an UTF-8 encode.
Improved the quoting of the credentials made by the CLI.
> Fix to LDAP RO group validation and CLI credentials quoting

- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
LDAP referrals seems to be a somewhat broken concept. By default the LDAP module uses a default anonymous bind to follow referrals which I would expect rarely (never) works. As NIPAP does not support setting up a separate connection for the referrals today, we just skip following them for now.
Also avoided sending full LDAP error messages to clients and instead make sure the error is logged.
> authlib: Avoid following LDAP referrals

- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
- nipap/nipap/xmlrpc.py
- nipap/requirements.txt
- pynipap/pynipap.py
Misc improvements of the JWT auth support:
* Make group claim name configurable (previously hard-coded to "group")
* Add support for bearer token auth in pynipap
* Cache signing keys
* Improvements to error handling
> Misc improvements of the JWT auth support

- nipap-cli/nipap
- pynipap/Makefile
- pynipap/pynipap/__init__.py
- pynipap/pynipap/pynipap.py
- pynipap/pynipap/tracing.py
- pynipap/setup.py
Mainly to avoid cluttering the global namespace with the name "tracing", moved the pynipap module to its own package.
The intention is that the package should be fully compatible with the stand-alone module and require no changes to the applications using it.
> pynipap as a package

- tests/test_rest.py
Validate the status code when performing REST queries and note message returned from the server if the validation fails.
Also replaced alot of json.loads() with req.json() to simplify a bit.
> Validate status code in REST tests

- nipap-www/entrypoint.sh
Changes to the nipap-www Docker setup to handle changes introduced by new packaging of nipap.
* Correct path to nipap-passwd
* Correct path to sample config file
> Docker fixes to WWW for new nipap packaging
