SpriteLink/NIPAP

- nipap/sql/ip_net.plsql
Not really sure how we should handle upgrades though!? Perhaps just
write something in the README that people need to think about this.
Fixes #341.
> Make pool and vrf names case-insensitive unique

- utilities/infoblox-import.py
Adds example infoblox utility that isn't 100% perfect but does the needful and adds all the attributes as tags.  The avps property could be explored as well but this is just an example utility.
> Add example infoblox import script

- nipap/nipap/backend.py
Obviously no one else uses a different port :-)
> pass port configuration paramater to driver

- .travis.yml
- nipap-cli/nipap
- nipap-cli/nipap.man.rst
- nipap-www/debian/postinst
- nipap/debian/nipapd.config
- nipap/debian/nipapd.postinst
- nipap/nipap-passwd
- nipap/nipap-passwd.man.rst
- nipap/nipapd
Merge of and some extra fixes to the original pull request to replace optparse with argparse by @dosomder, #573.
> Replace optparse with argparse

- nipap-www/nipapwww/public/controllers.js
Also fixes an incorrectly spelled word in a comment nearby.
> Fix confirmation message for when editing prefixes

- nipap-www/nipapwww/controllers/auth.py
As we wanted some changes to @dosomder's pull request #612 and he stated that he unfortunately cannot spend time on the project at the moment, I took the liberty to create a new pull request including the original commit and a further change making sure we're not exposing potentially sensitive data when an authentication error occurs.
> Modifications of dosomder's "Show authentication error in web-ui"

- nipap/nipap/backend.py
- tests/nipaptest.py
This fixes pool smart searching for tags.
> Fix pool tag searches

- nipap/nipap/backend.py
- tests/nipaptest.py
This fixes VRF smart searching for tags.
> Fix VRF tag searches

- nipap/nipap/backend.py
inherited_tags was simply missing..
Fixes #790.
> backend: add inherited_tags as prefix attribute

- nipap-www/nipapwww/controllers/auth.py
So this fixes the import of AuthError (that was easy!) and also makes the try/except clause a bit more inclusive to try and catch other potential auth errors.
> Fix authlib import + handle more exceptions

- nipap-cli/nipap.man.rst
> Fix manpage to tell about resizing pools

- nipap-www/nipapwww/controllers/xhr.py
- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/nipap.js
- nipap-www/nipapwww/templates/base.html
Make sure the VRF filter list is updated when a VRF in the filter list is removed from NIPAP.
> Update VRF filter when VRF is removed

- nipap/sql/triggers.plsql
If a prefix is shrunk we have to filter it out in the before trigger to
avoid selecting its old self as its parent_prefix. This is perfectly
natural as the database before trigger sees the data before the update
has been applied.
This fixes the scenario when trying to shrink an assignment prefix.
Before it would select itself as parent and when running the consistency
checks on that it would refuse the update as an assignment cannot have
an assignment (its old self) as a parent.
The prefix statistics were written under this false assumption, so with
the correct parent_prefix it would generate incorrect statistics which
I've solved by adding an explicit path for when shrinking prefixes, i.e.
NEW is smaller than OLD but indent level is the same.
This fixes #817.
> sql: fix parent_prefix selection

- nipap/nipap/backend.py
Adds a line explaining the equals_any operator.
Wording is somewhat improved and I've added some text explaining nesting
to combine multiple (more than two) terms using boolean operators.
Fixes #837.
> nipapd: add doc for equals_any operator

- README.md
This thing seems broken so I'm removing it.
> Remove BitDeli badge

- nipap/nipap/backend.py
- tests/nipaptest.py
> Block AVP with empty name in backend

- README.md
The pypi badge was broken so I switched to shields.io for that one.
IRC badge has a link to a web page that lets people join the IRC
channel. Not sure if that is good or bad yet.
> Add IRC badge + update pypi

- nipap/nipapd
> Updated syntax for psutil to find child processes

- jnipap/JnipapTester.java
- jnipap/jnipap/Pool.java
- jnipap/jnipap/Prefix.java
- jnipap/jnipap/VRF.java
Modified jnipap to accept new query interpretation format and added unit tests which perform smart_search-operations.
> jnipap: Accept new query interpretation format

- .travis.yml
- jnipap/JnipapTester.java
Despite the jnipap test suite being pretty small so far, we might just as well run it. I'm a bit unsure of how to perform the installations and tests properly, but it seems to work ;)
> Run jnipap test suite

- nipap-www/nipapwww/controllers/xhr.py
- nipap-www/nipapwww/public/nipap.js
- nipap/nipap/backend.py
This is just a bugfix PR for your PR #943 
This PR fixes a couple of places that was left out from the referenced PR.
> Support unlimited max_result for search_prefix (fixed)

- whoisd/README.rst
- whoisd/debian/control
> Fix spelling

- whoisd/nipap-whoisd
> whoisd: use argparse instead of optparse

- Dockerfile.nipapd
- nipap/debian/source/options
- nipap/entrypoint.sh
This adds a Dockerfile for nipapd and an entrypoint script which will
write the config file and launch nipapd.
This depends on #959.
> Dockerify nipapd

- nipap/nipap/backend.py
Added the prefix_length attribute to the documentation.
> Added prefix_length attribute to documentation

- nipap/nipap/smart_parsing.py
- tests/nipaptest.py
Handle unclosed single in addition to double quotes, including test cases. Also added test cases for unclosed parentheses.
> Handle unclosed single quote

- nipap-cli/nipap_cli/nipap_cli.py
- nipap-www/nipapwww/public/nipap.js
- nipap/nipap/backend.py
- nipap/nipap/smart_parsing.py
- pynipap/pynipap.py
- tests/nipaptest.py
- tests/xmlrpc.py
Okay, let's get another pair of eyes on some (heh, too many perhaps) improvements to the smart parser.
Most changes relates to improved error handling in the smart parser.
> Improvements of smart parser

- pynipap/pynipap.py
Updated the pynipap.xmlrpc_uri variable in the example given to match the default port and added the required corresponding path, "/XMLRPC".
Also added a note remote API connections.
Added an example on searching.
> pynipap.py commented documentation additions

- nipap-www/requirements.txt
Added a basic requirements.txt to the nipap-www package.
> Add requirements.txt

- nipap-www/nipapwww/controllers/xhr.py
- nipap-www/nipapwww/public/controllers.js
- nipap-www/nipapwww/public/directives.js
- nipap-www/nipapwww/public/nipap.js
Okay, another PR with way too many changes :smile:
To solve the problem with not being able to enter extra attributes with semicolons in them, I chose to change how the client side of the web interface sends data to the server side. Previously this was done with HTTP GET requests and the data was not URL encoded (thus the problem with semicolons, which actually wasn't limited to extra attributes, no fields could contain semicolons).
Instead of performing all this URL encoding and decoding, it seemed as a better solution to send the data (which was already in the form of a JavaScript object) as JSON in the body of a HTTP POST request, using a shorthand ```request.json``` attribute to decode the data into Python dicts at the receiving side. As the previous code sort of depended on behaviour …
> POST data to XHR functions

- NEWS
- nipap-cli/debian/changelog
- nipap-cli/nipap_cli/__init__.py
- nipap-www/debian/changelog
- nipap-www/nipap_www.egg-info/PKG-INFO
- nipap-www/nipapwww/__init__.py
- nipap/debian/changelog
- nipap/nipap/__init__.py
- pynipap/debian/changelog
- pynipap/pynipap.py
- whoisd/debian/changelog
- whoisd/nipap_whoisd.py
> Release 0.29.3

- README.md
> Add badge for QuantifiedCode

- docs/config-www.rst
- docs/install-unix.rst
- nipap-www/entrypoint.sh
- nipap-www/setup.py
Move the nipap-www.wsgi file to /etc/nipap/www.
Fixes #880.
> Move nipap-www.wsgi to /etc/nipap/www 

- nipap-www/nipapwww/public/nipap.js
Makes sure the HTTP POST requests made from nipap.js are sent with correct Content-Type.
Fixes #1060.
> Correct Content-Type in nipap.js

- Makefile
- nipap-cli/Makefile
- ojnipap/README.rst
- ojnipap/lib/.gitignore
- pynipap/Makefile
Some small fixes to build scripts, slightly improving the make clean target and adding a .gitignore file to make sure a directory is in place.
> Small improvements of build scripts

- docs/config-www.rst
I had missed a few of the locations.
> Correct location of nipap-www.ini

- nipap/nipap-passwd
Small change that makes it possible to use @ in the --username option argument to change auth_backend.
This only affect test-user.
> Fix for issue:#755 

- nipap-cli/nipap_cli/nipap_cli.py
> Small cleanup of nipap_cli, removed unused variable

- nipap/Makefile
- nipap/nipap/backend.py
- nipap/nipap/db_schema.py
- nipap/sql/Makefile
- nipap/sql/ip_net.plsql
- nipap/sql/upgrade-1-2.plsql
- nipap/sql/upgrade-2-3.plsql
- nipap/sql/upgrade-3-4.plsql
- nipap/sql/upgrade-4-5.plsql
- nipap/sql/upgrade-5-6.plsql
> Fixing database schema to be usable with databases not named "nipap"

- README.md
The duplicate hound review can be avoided by going to [Branch Settings](https://github.com/SpriteLink/NIPAP/settings/branchs) and disabling `hound`. The capitalized version of Hound is the one you want.
> Add a "Reviewed by Hound" badge and clean up other badges

- docs/config-www.rst
Clarified where the xmlrpc_uri config option should be set.
Fixes #1197
> Clarified WWW installation instructions

- .travis.yml
- nipap/nipap/__init__.py
- nipap/nipap/db_schema.py
- nipap/setup.py
- nipap/sql/ip_net.plsql
- nipap/sql/triggers.plsql
- nipap/sql/upgrade-6-7.plsql
Added what's needed to perform automatic upgrade of the database for the changes introduced in #1251.
> Add automatic db upgrade for fixed pool constraint

- .travis.yml
- nipap/requirements.txt
- tests/xmlrpc.py
Bump the test environment from Ubuntu Trusty to Bionic.
> Bump test environment to Ubuntu Bionic

- README.md
> Updated CI badge to refer to GitHub Actions

- .github/workflows/ci.yml
- nipap-cli/nipap
- nipap-cli/nipap_cli/nipap_cli.py
- nipap-cli/nipaprc
- nipap/nipap.conf.dist
- nipap/nipapd
- tests/test_rest.py
Add support for encrypting backend communication with TLS/SSL.
> Add SSL support

- NEWS
- nipap-cli/debian/changelog
- nipap-cli/nipap_cli/__init__.py
- nipap-www/debian/changelog
- nipap-www/nipap_www.egg-info/PKG-INFO
- nipap-www/nipapwww/__init__.py
- nipap/debian/changelog
- nipap/nipap/__init__.py
- pynipap/debian/changelog
- pynipap/pynipap.py
- whoisd/debian/changelog
- whoisd/nipap_whoisd.py
> Release v0.30.0

- nipap-www/nipapwww/controllers/prefix.py
- nipap-www/nipapwww/controllers/xhr.py
I stumbled across this route that exists but immediately throws a 500 because of a JSONDecodeError. Looking into the code, there was even more that didn't work. So I fixed it.
> Fix /prefix/add

- .github/workflows/ci.yml
- nipap/nipap/rest.py
- tests/test_rest.py
Added support for case insensitive search for string data values in the REST API  + added some new tests for the REST API.
Also improved the error handling a bit so that the error message is returned correctly.
> Restapi case insensitive search

- .github/workflows/ci.yml
- Dockerfile.www
- nipap-www/entrypoint.sh
- nipap-www/requirements.txt
- nipap/debian/control
- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
- nipap/nipap/rest.py
- nipap/nipap/xmlrpc.py
- nipap/requirements.txt
> JWT auth fixes

- nipap/nipap/backend.py
- nipap/nipap/rest.py
- tests/test_rest.py
Added support for editing prefixes to the REST API using the HTTP PUT request method.
> Added support for edit_prefix over REST

- nipap-www/nipapwww/public/controllers.js
The "Implied VRF" wasn't shown in the web interface, this is now fixed.
> Fixed display of pool implied VRF in web UI

- nipap-cli/helper-nipap
Small adjustment to comply with new behaviour of the configparser module.
> Update for new configparser

- Makefile
- nipap-cli/Makefile
- nipap-www/Makefile
- nipap/Makefile
- pynipap/Makefile
- whoisd/Makefile
Added some more files and folders to be remove when running make clean.
> Improved make clean

- NEWS
- nipap-cli/debian/changelog
- nipap-cli/nipap_cli/__init__.py
- nipap-www/debian/changelog
- nipap-www/debian/preinst
- nipap-www/debian/templates
- nipap-www/nipap_www.egg-info/PKG-INFO
- nipap-www/nipapwww/__init__.py
- nipap/debian/changelog
- nipap/nipap/__init__.py
- pynipap/debian/changelog
- pynipap/pynipap.py
- whoisd/debian/changelog
- whoisd/nipap_whoisd.py
Release 0.32.0.
Notifies the user when upgrading WWW from something earlier than 0.32 to something later than or equal to 0.32, as some action needs to be taken to upgrade the web UI.
> Release v0.32.0

- NEWS
- nipap-cli/debian/changelog
- nipap-cli/nipap_cli/__init__.py
- nipap-www/debian/changelog
- nipap-www/nipap_www.egg-info/PKG-INFO
- nipap-www/nipapwww/__init__.py
- nipap/debian/changelog
- nipap/nipap/__init__.py
- pynipap/debian/changelog
- pynipap/pynipap.py
- whoisd/debian/changelog
- whoisd/nipap_whoisd.py
> Release v0.32.2

- nipap/nipap/xmlrpc.py
Removed old debug logging and too wide exception handler.
> Removed old debugging stuff

- nipap/nipap.conf.dist
- nipap/nipap/authlib.py
Add support for a list of group claim names in JWT authentication.
> nipapd: Support multiple claims in JWT auth

- docs/config-cli.rst
Update nipap-passwd command sample
> Update nipap-passwd command sample 

- nipap/nipapd
To avoid race conditions when accessing the database, wait with setting up nipapd (and thus connecting to the databae) until after forking.
> Setup nipapd after forking

- whoisd/nipap-whoisd
Fixed two bugs in the whois-daemon:
* Handle inline comments
* Use correct opts to open() when opening pid file
> Bugfixes to the whois-daemon

- nipap/nipap/backend.py
> Fix typo when searching pools

- .github/workflows/ci.yml
- Dockerfile.nipapd
- Dockerfile.www
* Set min severity from info to warning
* Set severity of non-pinned pip3 install-command to info
* Replace deprecated MAINTAINER with LABEL
> Handle some Hadolint errors
